### ISSUE TITLE
Integrarea SvClient in ServerCommunicator / mutarea functionalitatii intr-o componenta comuna.

### ISSUE THREAD

**Issue by dobrealexandru** [codrinalexandru/stocks-management#1]
Deoarece ServerCommunicator si SvClient impart functionalitate (IsConnected, Read, Write), se preteaza reutilizarea codului intr-un mod curat. 

In acest sens, eu vad cateva optinui: 
- Agregarea SvClient in ServerCommunicator.
- Mutarea functionalitatii din SvClient (IsConnected, Read, Write) intr-o clasa de baza din care sa mosteneasca ambele clase. (ServerCommunicator/SvClient).
- Mutarea functionalitatii in metode statice care sa fie apelate in ambele clase. 

Trebuie sa discutam pentru a ajunge la o solutie optima. De asemenea, in masura in care SvClient nu va fi utilizata de ServerCommuicator, se preteaza mutarea clasei in CDIM.ServerClientModel.Server.

**Comment by dobrealexandru** [comment]
Propun crearea unei clase abstracte (NetworkCommunicator?) care sa contina un Socket, si cele trei metode (IsConnected, Read, Write), din care sa mosteneasca ServerCommunicator si SvClient. Clasa va fi pusa in ns. Commons, iar SvClient va fi mutata in ns. Servers.

**Comment by m-doru** [comment]
Sunt de acord ca asta ar fi cea mai buna alternativa. Plus ca se incadreaza perfect NetworkCommunicator in ns. Commons si in felul asta nu fortam nimic.

**Comment by dobrealexandru** [comment]
In cazul asta, sa facem un task pe Trello, un branch pentru task si sa implementam. Cine se baga? Eu pot deabea dupa program, adica pe la 21:00.
